version: '3.8'

services:
  panel:
    build: .
    ports:
      - "80:80"
    environment:
      - APP_URL=http://localhost
      - DB_HOST=database
      - DB_DATABASE=finexlyx
      - DB_USERNAME=finexlyx
      - DB_PASSWORD=secret
    volumes:
      - ./:/var/www/html
    depends_on:
      - database
      - redis

  database:
    image: mariadb:10.5
    environment:
      - MYSQL_DATABASE=finexlyx
      - MYSQL_USER=finexlyx
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=secret
    volumes:
      - db_data:/var/lib/mysql

  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data

volumes:
  db_data:
  redis_data: